from azure.search.documents.indexes.models import (
    ComplexField,
    HnswAlgorithmConfiguration,
    SearchField,
    SearchFieldDataType,
    SearchIndex,
    SearchableField,
    SimpleField,
    VectorSearch,
    VectorSearchProfile,
)

DEFAULT_CHUNK_CONTAINER = "chunk-container"
DEFAULT_TARGET_INDEX_NAME = "rag-index"
DEFAULT_DATASOURCE_NAME = "rag-datasource"
DEFAULT_SKILLSET_NAME = "rag-skillset"
DEFAULT_INDEXER_NAME = "rag-indexer"
VECTOR_ALGORITHM_NAME = "vector-hnsw"
VECTOR_PROFILE_NAME = "vector-profile"


def build_shared_index(*, name: str = DEFAULT_TARGET_INDEX_NAME, embedding_dimensions: int) -> SearchIndex:
    return SearchIndex(
        name=name,
        fields=[
            SimpleField(
                name="id",
                type=SearchFieldDataType.String,
                key=True,
                filterable=True,
                hidden=False,
            ),
            ComplexField(
                name="metadata",
                fields=[
                    SearchableField(
                        name="source_type",
                        type=SearchFieldDataType.String,
                        filterable=True,
                        facetable=True,
                        hidden=False,
                    ),
                    SearchableField(
                        name="category",
                        type=SearchFieldDataType.String,
                        filterable=True,
                        facetable=True,
                        hidden=False,
                    ),
                    SearchableField(
                        name="topic",
                        type=SearchFieldDataType.String,
                        filterable=True,
                        facetable=True,
                        hidden=False,
                    ),
                    SearchableField(
                        name="subtopic",
                        type=SearchFieldDataType.String,
                        filterable=True,
                        facetable=True,
                        hidden=False,
                    ),
                    SimpleField(
                        name="source_url",
                        type=SearchFieldDataType.String,
                        filterable=True,
                        hidden=False,
                    ),
                    SearchableField(
                        name="source_url_text",
                        type=SearchFieldDataType.String,
                        filterable=True,
                        hidden=False,
                    ),
                    SearchableField(
                        name="source_name",
                        type=SearchFieldDataType.String,
                        filterable=True,
                        hidden=False,
                    ),
                    ComplexField(
                        name="image",
                        fields=[
                            SimpleField(
                                name="page_number",
                                type=SearchFieldDataType.Int32,
                                filterable=True,
                                sortable=True,
                                facetable=True,
                                hidden=False,
                            ),
                            SearchableField(
                                name="figure_id",
                                type=SearchFieldDataType.String,
                                filterable=True,
                                hidden=False,
                            ),
                            SearchableField(
                                name="summary_method",
                                type=SearchFieldDataType.String,
                                filterable=True,
                                facetable=True,
                                hidden=False,
                            ),
                            ComplexField(
                                name="bounding_regions",
                                collection=True,
                                fields=[
                                    SimpleField(
                                        name="page_number",
                                        type=SearchFieldDataType.Int32,
                                        filterable=True,
                                        hidden=False,
                                    ),
                                    SearchField(
                                        name="polygon",
                                        type=SearchFieldDataType.Collection(SearchFieldDataType.Double),
                                        searchable=False,
                                        hidden=False,
                                    ),
                                ],
                            ),
                            SearchableField(
                                name="ocr_text",
                                type=SearchFieldDataType.String,
                                hidden=False,
                            ),
                            SearchableField(
                                name="caption",
                                type=SearchFieldDataType.String,
                                hidden=False,
                            ),
                        ],
                    ),
                ],
            ),
            SearchableField(
                name="content",
                type=SearchFieldDataType.String,
                hidden=False,
            ),
            SearchField(
                name="contentVector",
                type=SearchFieldDataType.Collection(SearchFieldDataType.Single),
                searchable=True,
                hidden=False,
                stored=True,
                vector_search_dimensions=embedding_dimensions,
                vector_search_profile_name=VECTOR_PROFILE_NAME,
            ),
        ],
        vector_search=VectorSearch(
            algorithms=[HnswAlgorithmConfiguration(name=VECTOR_ALGORITHM_NAME)],
            profiles=[
                VectorSearchProfile(
                    name=VECTOR_PROFILE_NAME,
                    algorithm_configuration_name=VECTOR_ALGORITHM_NAME,
                )
            ],
        ),
    )
